// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1Hl5KexRX8ov7ZlDMEqE85grmdGr8zDM',
    appId: '1:417490407531:web:3f2186e54a5b773fb8e12e',
    messagingSenderId: '417490407531',
    projectId: 'crew-test-2db02',
    authDomain: 'crew-test-2db02.firebaseapp.com',
    storageBucket: 'crew-test-2db02.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp5ZOL1NsXlK3WMHmvS15GnnnnI4DGRFE',
    appId: '1:417490407531:android:b179df3a1958afe9b8e12e',
    messagingSenderId: '417490407531',
    projectId: 'crew-test-2db02',
    storageBucket: 'crew-test-2db02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq4rifkw2vHynkjO5Qdi26Qf2ohhBVGwk',
    appId: '1:417490407531:ios:e2fed2effbd31d4cb8e12e',
    messagingSenderId: '417490407531',
    projectId: 'crew-test-2db02',
    storageBucket: 'crew-test-2db02.firebasestorage.app',
    iosBundleId: 'com.example.crewApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq4rifkw2vHynkjO5Qdi26Qf2ohhBVGwk',
    appId: '1:417490407531:ios:e2fed2effbd31d4cb8e12e',
    messagingSenderId: '417490407531',
    projectId: 'crew-test-2db02',
    storageBucket: 'crew-test-2db02.firebasestorage.app',
    iosBundleId: 'com.example.crewApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1Hl5KexRX8ov7ZlDMEqE85grmdGr8zDM',
    appId: '1:417490407531:web:f2aaded43d984d35b8e12e',
    messagingSenderId: '417490407531',
    projectId: 'crew-test-2db02',
    authDomain: 'crew-test-2db02.firebaseapp.com',
    storageBucket: 'crew-test-2db02.firebasestorage.app',
  );
}
